state_publisher:
  ros__parameters:
    a1: 0.0
    a2: 0.0
    a3: 3.0
    d1: 2.0
    d2: 0.0
    d3: 0.0
    alpha1: 0.0
    alpha2: 0.0
    alpha3: 0.0
    theta1: 0.0
    theta2: -1.57
    theta3: 1.57
